#include <iostream>
#include <memory>
#include "../../include/ir.h"

namespace tang {
namespace ir {

// 简化的IR模块实现
std::shared_ptr<Module> generateIR(const std::shared_ptr<tang::Module>& ast) {
    // 创建一个空的IR模块
    auto module = std::make_shared<Module>();
    
    // 这里应该实现AST到IR的转换
    // 现在只返回一个空模块作为占位符
    std::cout << "IR generation: Converted " << ast->functions.size() << " functions" << std::endl;
    
    return module;
}

// 简化的x86-64代码生成器工厂
std::unique_ptr<CodeGenerator> createX86_64CodeGenerator() {
    // 返回一个简单的代码生成器
    class SimpleX86_64CodeGenerator : public CodeGenerator {
    public:
        void generateCode(const Module& module, const std::string& output_file) override {
            std::cout << "Code generation: Generating x86-64 assembly for " 
                      << module.functions.size() << " functions to " << output_file << std::endl;
            
            // 创建简单的汇编文件
            std::ofstream file(output_file);
            file << "; Generated by Tang Compiler\n";
            file << ".text\n";
            file << ".global _start\n";
            file << "\n";
            file << "_start:\n";
            file << "    mov $60, %rax\n";
            file << "    mov $0, %rdi\n";
            file << "    syscall\n";
            file.close();
        }
    };
    
    return std::make_unique<SimpleX86_64CodeGenerator>();
}

// 简化的IR打印函数
void printIR(const Module& module) {
    std::cout << "=== IR Module ===" << std::endl;
    std::cout << "Functions: " << module.functions.size() << std::endl;
    
    for (const auto& func : module.functions) {
        std::cout << "Function: " << func.name << std::endl;
        std::cout << "  Basic blocks: " << func.basic_blocks.size() << std::endl;
    }
}

} // namespace ir
} // namespace tang